model:
  large_model:
    name: 'vit_base_patch16_224'
    pretrained: True
    lr: 0.001
  small_model:
    name: 'mobilevit_s'
    pretrained: True
    lr: 0.001

dataset:
  name: 'ImageNet-C'
  path: './data/ImageNet-C'
  batch_size: 32
  # 64 in RTX 4080 Super(16GB) will cause OOM

coca:
  lambda_co_adaptation: 1.0
  lambda_self_adaptation: 1.0 